### ISSUE TITLE
Cant run on Fedora 27,28,29

### ISSUE THREAD

**Issue by skysoulkeeper** [ftsiadimos/netspy2ban#1]
When i try to start netspy2start

Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/netspy2ban/netspy2ban", line 182, in <module>
    app = MyApp()
  File "/usr/lib64/python2.7/site-packages/wx-3.0-gtk3/wx/_core.py", line 8628, in __init__
    self._BootstrapApp()
  File "/usr/lib64/python2.7/site-packages/wx-3.0-gtk3/wx/_core.py", line 8196, in _BootstrapApp
    return _core_.PyApp__BootstrapApp(*args, **kwargs)
  File "/usr/lib/python2.7/site-packages/netspy2ban/netspy2ban", line 176, in OnInit
    frame = Mainpy(None, -1, 'NetSpy2ban')
  File "/usr/lib/python2.7/site-packages/netspy2ban/netspy2ban", line 69, in __init__
    self.panel2 = Fail2banclass(self)
  File "/usr/lib/python2.7/site-packages/netspy2ban/fail2ban.py", line 48, in __init__
    banti = self.parser.getint('DEFAULT', 'bantime')
  File "/usr/lib64/python2.7/ConfigParser.py", line 359, in getint
    return self._get(section, int, option)
  File "/usr/lib64/python2.7/ConfigParser.py", line 356, in _get
    return conv(self.get(section, option))
ValueError: invalid literal for int() with base 10: '10m'

I am installing netspy2ban from rpm package

PLS help with this ...

**Comment by ftsiadimos** [comment]
I apologize for the delay. 

The fail2ban has changed the config file and the values are not int. After you install the rpm modify the below file:
```
# vim /usr/lib/python2.7/site-packages/netspy2ban/fail2ban.py
```
and replace the lines from the file with the below lines:   
```
48         banti = self.parser.get('DEFAULT', 'bantime')
49         findti = self.parser.get('DEFAULT', 'findtime')
59         self.box1.SetValue(int(banti))
62         self.box2.SetValue(int(findti))
```
after that it is going to work.

Keep in mind that it works only for 'gnome classic' and NOT for 'gnome wayland'. The python wx library is not supported there.
